Task_1_1_2
ArtemChepenkov/OOP pull request #12
Opened 2024-09-24 09:04 UTC by ArtemChepenkov

2024-09-24 12:34 UTC, shadrina requested changes

2024-09-24 12:34 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chepenkov/blackjack/Card.java
> +    private String name;
Финальные?

2024-09-24 12:34 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chepenkov/blackjack/CardDeck.java
> +                              "Король", "Туз"};
Сделай пожалуйста enum'ы. Это как раз конструкция для описания фиксированного множества значений.

2024-09-24 12:34 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chepenkov/blackjack/CardDeck.java
> +    Card[] cards;
Видимость? Почему массив, а не список? Список скорее всего будет поудобнее.

2024-09-24 12:34 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chepenkov/blackjack/CardDeck.java
> +
Оно может выкинуть [ArrayIndexOutOfBoundsException](https://docs.oracle.com/javase/8/docs/api/java/lang/ArrayIndexOutOfBoundsException.html)?

2024-09-24 12:34 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chepenkov/blackjack/Table.java
> +        return true;
Наверно Идея упорно предлагает это упростить.

2024-09-24 12:34 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chepenkov/blackjack/Table.java
> +     * Сеттер для счёта игрока.
Точно все эти геттеры нужны?

2024-09-24 12:34 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chepenkov/blackjack/Table.java
> +     * Сеттер для счёта игрока.
Если что-то не нужно, не нужно это писать.

2024-09-24 12:59 UTC, ArtemChepenkov commented on Task_1_1_2/src/main/java/ru/nsu/chepenkov/blackjack/CardDeck.java
> +
Нет, т.к. у меня указано, что две колоды, которые в свою очередь пересобираются после каждого раунда

2024-09-24 13:55 UTC, ArtemChepenkov commented on Task_1_1_2/src/main/java/ru/nsu/chepenkov/blackjack/Table.java
> +     * Сеттер для счёта игрока.
Да, я проверил, Идея не пишет "no usage"

2024-10-01 08:46 UTC, shadrina approved these changes

2024-10-01 08:49 UTC, merged